genernal:
  label: 基本设置
  items:
    background_picture:
      name: background_picture
      label: 首页背景图
      type: attachment
      default: '/themes/Fantasy/source/images/background.png'
    site_custom_style:
      name: site_custom_style
      label: 自定义CSS样式
      type: textarea
social:
  label: 社交信息
  items:
    social_github:
      name: social_github
      label: Github主页链接
      type: text
      default: ""
      description: "留空则不展示"
    social_weibo:
      name: social_weibo
      label: 微博主页链接
      type: text
      default: ""
      description: "留空则不展示"
    social_twitter:
      name: social_twitter
      label: Twitter主页链接
      type: text
      default: ""
      description: "留空则不展示"
    social_qq:
      name: social_qq
      label: QQ号
      type: text
      default: ""
      description: "留空则不展示"
beian:
  label: 备案信息
  items:
    icp_info:
      name: icp_info
      label: ICP备案号
      type: text
      default: ""
      description: "留空则不展示ICP备案号"
    ga_info:
      name: ga_info
      label: 公安备案号
      type: text
      default: ""
      description: "留空则不展示公安备案号"
plugins:
  label: 插件设置
  items:
    hitokoto_bool:
      name: hitokoto_bool
      label: 一言
      type: radio
      data-type: bool
      default: false
      description: '是否展示一言'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    created_time:
      name: created_time
      label: 建站时间
      type: text
      default: ""
      description: "格式: 2022/01/01 留空则不展示"
    bangumi_user:
      name: bangumi_user
      label: Bangumi用户名
      type: text
      default: ""
      description: "Bangumi用户名"
    aplayer_id:
      name: aplayer_id
      label: 音乐/歌单 ID
      type: text
      default: ""
      description: "网易云音乐的歌单/音乐 ID"